module.exports = [
  // PUSH
  { id:'push_up', name:'Push-Up', muscle:'Chest · Triceps · Shoulders', category:'push', image:'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600&q=80', cues:['Hands just outside shoulder-width','Core braced throughout','Lower chest to 1" from floor','Press to full lockout'], defaultSets:3, defaultReps:15, rest:60 },
  { id:'bench_press', name:'Bench Press', muscle:'Chest · Triceps · Front Delts', category:'push', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80', cues:['Retract & depress scapula','Bar touches lower chest','Drive feet into floor','2s controlled descent'], defaultSets:4, defaultReps:8, rest:90 },
  { id:'overhead_press', name:'Overhead Press', muscle:'Shoulders · Triceps', category:'push', image:'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80', cues:['Brace core like a plank','Perfectly vertical bar path','Push head through at lockout','Full overhead lockout'], defaultSets:3, defaultReps:10, rest:90 },
  { id:'dumbbell_fly', name:'Dumbbell Fly', muscle:'Chest (isolation)', category:'push', image:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80', cues:['Fixed slight elbow bend','Feel deep stretch at bottom','Squeeze pecs hard at top','Arc motion, not press'], defaultSets:3, defaultReps:12, rest:60 },
  { id:'tricep_dip', name:'Tricep Dip', muscle:'Triceps · Lower Chest', category:'push', image:'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600&q=80', cues:['Lean slightly forward','Elbows track backward','Lower to 90° elbow bend','Full lockout at top'], defaultSets:3, defaultReps:12, rest:60 },
  { id:'lateral_raise', name:'Lateral Raise', muscle:'Side Deltoid', category:'push', image:'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80', cues:['Slight forward torso lean','Lead with elbows','Stop at shoulder height','3s slow negative'], defaultSets:3, defaultReps:15, rest:45 },
  // PULL
  { id:'pull_up', name:'Pull-Up', muscle:'Lats · Biceps · Rear Delts', category:'pull', image:'https://images.unsplash.com/photo-1616803689943-5601631c7fec?w=600&q=80', cues:['Full dead hang start','Depress shoulders first','Pull elbows to pockets','Chin clearly clears bar'], defaultSets:4, defaultReps:8, rest:90 },
  { id:'barbell_row', name:'Barbell Row', muscle:'Mid Back · Lats · Biceps', category:'pull', image:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80', cues:['Hinge to 45° torso','Bar to lower sternum','Squeeze shoulder blades','No hip drive'], defaultSets:4, defaultReps:8, rest:90 },
  { id:'lat_pulldown', name:'Lat Pulldown', muscle:'Lats · Teres Major · Biceps', category:'pull', image:'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80', cues:['Wide overhand grip','Slight backward lean','Pull to upper chest','Full stretch at top'], defaultSets:3, defaultReps:12, rest:60 },
  { id:'seated_row', name:'Seated Cable Row', muscle:'Mid Back · Rhomboids', category:'pull', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80', cues:['Sit tall, chest up','Pull to lower sternum','Retract blades fully','Reach forward for stretch'], defaultSets:3, defaultReps:12, rest:60 },
  { id:'bicep_curl', name:'Barbell Curl', muscle:'Biceps · Brachialis', category:'pull', image:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&q=80', cues:['Elbows pinned to sides','Supinate wrist at top','Squeeze 1 second at peak','3s controlled eccentric'], defaultSets:3, defaultReps:12, rest:60 },
  { id:'face_pull', name:'Face Pull', muscle:'Rear Delts · Traps · Rotator Cuff', category:'pull', image:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80', cues:['Cable at eye level','Pull to face, elbows high','External rotate at end','Slow and deliberate'], defaultSets:3, defaultReps:15, rest:45 },
  // LEGS
  { id:'squat', name:'Back Squat', muscle:'Quads · Glutes · Hamstrings · Core', category:'legs', image:'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600&q=80', cues:['Feet shoulder-width, toes out','Break parallel every rep','Drive knees out over toes','Brace core hard throughout'], defaultSets:4, defaultReps:6, rest:120 },
  { id:'deadlift', name:'Deadlift', muscle:'Hamstrings · Glutes · Erectors · Traps', category:'legs', image:'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&q=80', cues:['Bar over mid-foot always','Big breath — brace hard','Push floor away','Lock hips out fully'], defaultSets:4, defaultReps:5, rest:180 },
  { id:'lunge', name:'Walking Lunge', muscle:'Quads · Glutes · Hip Flexors', category:'legs', image:'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=600&q=80', cues:['Large forward step','Back knee near floor','Torso stays upright','Drive through front heel'], defaultSets:3, defaultReps:20, rest:60 },
  { id:'leg_press', name:'Leg Press', muscle:'Quads · Glutes · Calves', category:'legs', image:'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&q=80', cues:['Feet mid-platform height','Never lock knees out','Full range of motion','2s controlled negative'], defaultSets:3, defaultReps:12, rest:90 },
  { id:'rdl', name:'Romanian Deadlift', muscle:'Hamstrings · Glutes · Erectors', category:'legs', image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80', cues:['Slight soft knee bend','Push hips back, not down','Bar stays close to legs','Feel full hamstring stretch'], defaultSets:3, defaultReps:10, rest:90 },
  { id:'calf_raise', name:'Calf Raise', muscle:'Gastrocnemius · Soleus', category:'legs', image:'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80', cues:['Full stretch at bottom','1s pause at peak','4s slow eccentric','No bouncing'], defaultSets:4, defaultReps:20, rest:45 },
  // CORE
  { id:'plank', name:'Plank', muscle:'Transverse Abs · Obliques · Glutes', category:'core', image:'https://images.unsplash.com/photo-1591291621164-2c6367723315?w=600&q=80', cues:['Forearms parallel under shoulders','Hips perfectly level','Squeeze abs, glutes, quads','Breathe steadily'], defaultSets:3, defaultReps:1, rest:60, isTime:true, duration:45 },
  { id:'crunch', name:'Crunch', muscle:'Rectus Abdominis', category:'core', image:'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80', cues:['Hands lightly behind ears','Curl shoulders off mat','Do not pull on neck','Squeeze abs at top'], defaultSets:3, defaultReps:20, rest:45 },
  { id:'leg_raise', name:'Hanging Leg Raise', muscle:'Lower Abs · Hip Flexors', category:'core', image:'https://images.unsplash.com/photo-1616803689943-5601631c7fec?w=600&q=80', cues:['Full dead hang start','Zero kipping or swinging','Raise legs to 90°+','Lower slowly with control'], defaultSets:3, defaultReps:12, rest:60 },
  { id:'mountain_climber', name:'Mountain Climber', muscle:'Core · Cardio · Hip Flexors', category:'core', image:'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=600&q=80', cues:['High plank position','Drive knees alternately to chest','Move fast, hips stay stable','Breathe rhythmically'], defaultSets:3, defaultReps:30, rest:45 },
  // CARDIO
  { id:'burpee', name:'Burpee', muscle:'Full Body · Cardiovascular', category:'cardio', image:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80', cues:['Squat down, hands to floor','Jump feet back to plank','Optional push-up at bottom','Explosive jump up, clap overhead'], defaultSets:3, defaultReps:10, rest:60 },
  { id:'jump_rope', name:'Jump Rope', muscle:'Calves · Cardio · Coordination', category:'cardio', image:'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80', cues:['Light on feet','Small efficient jumps','Rotation from wrists','Relax shoulders and arms'], defaultSets:3, defaultReps:1, rest:60, isTime:true, duration:60 },
  { id:'box_jump', name:'Box Jump', muscle:'Power · Quads · Glutes · Calves', category:'cardio', image:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80', cues:['Explosive arm swing forward','Full hip extension','Land softly with bent knees','Always step down — never jump'], defaultSets:4, defaultReps:8, rest:90 },
]